### PR TITLE
Changes for Pyodide 0.26.4

### PR DESCRIPTION
**Pull request by hoodmane**
These are the changes to `src/pyodide` needed to use Pyodide 0.26.4.

### CODE REVIEW

**Review by danlapid — APPROVED** [review]
LGTM

**Comment by hoodmane** [comment]
Seems to be a real windows failure though:
```
ERROR: D:/a/workerd/workerd/src/pyodide/BUILD.bazel:225:13: Transpiling & type-checking TypeScript project @//src/pyodide:pyodide@tsproject [tsc -p src/pyodide/tsconfig.json] failed: (Exit 1): tsc.bat failed: error executing TsProject command (from target //src/pyodide:pyodide@tsproject) 
error TS5055: Cannot write file 'C:/tmp/hs7imhxj/execroot/workerd/bazel-out/x64_windows-opt/bin/src/pyodide/internal/pool/esbuild.config.mjs' because it would overwrite input file.
```

**Comment by hoodmane** [comment]
I don't understand how this could cause it though...

**Comment by hoodmane** [comment]
Nevermind just a flake.

**Pull request merged**
