### PR TITLE
[nfc] ruff: disable too many branches/statements

### PR DESCRIPTION
**Pull request by mikea**
Imo these are arbitrary and are often fought with.

### CODE REVIEW

**Comment by npaun** [comment]
Pretty meh on this one. I dislike long and complex functions, but those limits seem low.

**Comment by mikea** [comment]
>  I dislike long and complex functions

This is what code-reviewers are for. As it is I can't land simple script just because it has 52 statements and not 50. Don't know who benefits from this one.

**Review by npaun — APPROVED** [review]
That is annoying. Nuke away.

**Review by anonrig — APPROVED** [review]

**Comment by hoodmane** [comment]
Thanks @mikea!

**Pull request merged**
