### PR TITLE
Revert "Merge pull request #2970 from cloudflare/kenton/sqlite-statem…

### PR DESCRIPTION
**Pull request by justin-mp**
…ent-cache-3"

This reverts commit 9326b8a5c1bdf5cef9616d750d56b5f7152c3ed0, reversing changes made to bbde7e4f9352be729c0daa379d23a9ecbea44585.

We believe that the SQLite query cache has lead to a latency increase for many workloads.

### CODE REVIEW

**Comment by justin-mp** [comment]
> Does this require a matching internal pr?

Yes.  See 9194.  I needed to push this to know what PR number to include in the internal PR.

**Review by danlapid — APPROVED** [review]

**Comment by kentonv** [comment]
This could break anyone who has become dependent on the ability to pass multiple statements at a time to D1's `prepare()` API.

**Comment by isaac-mcfadyen** [comment]
> This could break anyone who has become dependent on the ability to pass multiple statements at a time to D1's `prepare()` API.

FWIW we see this frequently from users on the Cloudflare Developers Discord so definitely a valid concern.

**Comment by justin-mp** [comment]
See #3117 for a better fix.

**Pull request closed without merging**
