### PR TITLE
Add getDatabaseSize() method to Sqlite-KV to retrieve size of database

### PR DESCRIPTION
**Pull request by shrima-cf**
I will be using this in my metrics

### CODE REVIEW

**Comment by shrima-cf** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by a-robinson — COMMENTED** [review]
The code looks fine, although I have to admit I'm not sure what this will be used for that we couldn't have used [`SqlStorage::getDatabaseSize()`](https://github.com/cloudflare/workerd/blob/main/src/workerd/api/sql.h#L31) for. I assume that will make more sense after seeing the code that uses this, but want to call it out just in case you missed it.

**Comment by shrima-cf** [comment]
> The code looks fine, although I have to admit I'm not sure what this will be used for that we couldn't have used [`SqlStorage::getDatabaseSize()`](https://github.com/cloudflare/workerd/blob/main/src/workerd/api/sql.h#L31) for. I assume that will make more sense after seeing the code that uses this, but want to call it out just in case you missed it.

The KV api layer operates on the DB object directly as opposed to going through SqlStorage, so need this method on the DB object itself.
We could remove the ones in SqlStorage and let it call db.getDatabaseSize(), I did not do that in this change

**Comment by a-robinson** [comment]
But what part of the KV API layer is going to be calling this code? That's what I'm missing.

**Comment by kentonv** [comment]
`SqliteKv` is a small utility class that is intended only to implement the KV storage API on top of Sqlite. `getDatabaseSize()` doesn't seem to have anything to do with KV storage specifically, so it doesn't seem like it belongs here.

Also, the workers runtime (internal codebase) already tracks the current database size at all times through a different method (by intercepting and inspecting WAL writes), so obtaining it by executing a pragma seems unnecessary -- we can just use the value we already have.

Look for `lastCommittedDbSize` in the internal codebase.

**Comment by shrima-cf** [comment]
> But what part of the KV API layer is going to be calling this code? That's what I'm missing.

Here is how I plan to do the changes:
actor-state.c++ is where we emit the metrics ([here](https://github.com/cloudflare/workerd/blob/main/src/workerd/api/actor-state.c%2B%2B#L259)). I want to emit the databaseSize here.
I plan to get the databaseSize returned from of getCache(..).get(key,value).
In the kv implementation of get(from above), I need the getDatabaseSize() method so I can return the value.

**Comment by justin-mp** [comment]
> I think it could make sense to extend `ActorStorageInterface` with a `getDatabaseSize()` method, which the internal codebase can implement in terms of `lastCommittedDbSize`, but workerd could implement using the pragma. But that'd still happen in `ActorSqlite`, not `SqliteKv`.

I don't think the `lastCommittedDbSize` is the same what we get from the SQL query using pragma.  I believe `lastCommittedDbSize` is the size of the DB on disk, while the pragma-based calculation removes free pages from the calculation, so it should be strictly smaller.

**Comment by kentonv** [comment]
We use auto-vacuum so I think free pages are eliminated immediately?

**Comment by shrima-cf** [comment]
Decided to take a different approach for this task, the PR is no longer needed

**Pull request closed without merging**
