### PR TITLE
Revert "stack-trace symbolizer using llvm-symbolizer subprocess"

### PR DESCRIPTION
**Pull request by ObsidianMinor**
Reverts cloudflare/workerd#297

This broken an internal build. Somehow.

### CODE REVIEW

**Comment by ObsidianMinor** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ObsidianMinor** [comment]
Oh _now_ you accept that I've signed the CLA

**Comment by ObsidianMinor** [comment]
@mikea fyi

**Comment by dom96** [comment]
hm, seems the CI is taking a long time. I see cache errors in the logs, I guess the cache is down or @ObsidianMinor doesn't have access to it?

**Comment by harrishancock** [comment]
He doesn't have access (yet). cc @byule

**Review by harrishancock — APPROVED** [review]

**Pull request merged**
