### PR TITLE
upgrade rust toolchain to 1.72.1

### PR DESCRIPTION
**Pull request by fhanau**
[WIP]

### CODE REVIEW

**Comment by fhanau** [comment]
Mike previously tried to update to 1.72.1 (https://github.com/cloudflare/workerd/pull/1260), which did not work due to compile errors on Windows. I instead upgraded to 1.69.0 for the time being as 1.70 is the first version that breaks.
I believe this is caused by rust using LLVM16 starting with [1.70](https://releases.rs/docs/1.70.0/#internal-changes). I tried 1.73.0 in this PR to see if that changes things (1.73 uses LLVM17 already), but that still has the same link errors.
The error output refers to missing symbols when linking the workerd binary. [One source](https://users.rust-lang.org/t/rust-compiler-error-when-linking-with-windows-dll/98504 
) with similar issues suggests that linking ntdll.lib would solve this, but hopefully there's a better workaround.
@ObsidianMinor @ohodson Since y'all have worked with Rust/fixing the Windows build, any ideas?

**Comment by mikea** [comment]
to save you some clicks here are unresolved symbols:

```
lld-link: error: undefined symbol: __declspec(dllimport) NtCreateFile
>>> referenced by /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\windows\fs.rs:829
>>>               rust_deps.lib(std-287abad1c0bdb9b8.std.2781fb3ad214b392-cgu.0.rcgu.o):(std::sys::windows::fs::open_link_no_reparse::h2951eea6795ed2d0)

lld-link: error: undefined symbol: __declspec(dllimport) RtlNtStatusToDosError
>>> referenced by /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\windows\fs.rs:858
>>>               rust_deps.lib(std-287abad1c0bdb9b8.std.2781fb3ad214b392-cgu.0.rcgu.o):(std::sys::windows::fs::open_link_no_reparse::h2951eea6795ed2d0)
>>> referenced by /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\windows\handle.rs:273
>>>               rust_deps.lib(std-287abad1c0bdb9b8.std.2781fb3ad214b392-cgu.0.rcgu.o):(std::sys::windows::handle::Handle::synchronous_read::h2daccb4eddab61b0)
>>> referenced by /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\windows\handle.rs:319
>>>               rust_deps.lib(std-287abad1c0bdb9b8.std.2781fb3ad214b392-cgu.0.rcgu.o):(std::sys::windows::handle::Handle::synchronous_write::h52324ccada88a341)

lld-link: error: undefined symbol: __declspec(dllimport) NtReadFile
>>> referenced by /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\windows\handle.rs:242
>>>               rust_deps.lib(std-287abad1c0bdb9b8.std.2781fb3ad214b392-cgu.0.rcgu.o):(std::sys::windows::handle::Handle::synchronous_read::h2daccb4eddab61b0)

lld-link: error: undefined symbol: __declspec(dllimport) NtWriteFile
>>> referenced by /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library\std\src\sys\windows\handle.rs:291
>>>               rust_deps.lib(std-287abad1c0bdb9b8.std.2781fb3ad214b392-cgu.0.rcgu.o):(std::sys::windows::handle::Handle::synchronous_write::h52324ccada88a341)
```

they do look like they are coming from `ntdll`. I wonder why rust doesn't add it itself?

**Comment by fhanau** [comment]
Well, that turned out to be easier than expected, the simplest approach conceivable for linking ntdll.lib worked. I changed the version back to 1.72.1 so that the LLVM used for compiling Rust is not too out-of-sync with the one used to compile C++ code.

This should be ready for review, unless you have ideas for what's causing this/want to track it down.

**Review by dom96 — APPROVED** [review]
Huh, I'd expect ntdll to be dynamically linked. I guess our Rust build is forcing static linking, I suppose that's fine as long as it works.

**Comment by ohodson** [comment]
> Huh, I'd expect ntdll to be dynamically linked. I guess our Rust build is forcing static linking, I suppose that's fine as long as it works.

`ntdll.dll` is a dynamic library and`ntdll.lib` is the corresponding import library for `ntdll.dll`:
* https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-creation#creating-an-import-library
* https://en.wikipedia.org/wiki/Dynamic-link_library#Import_libraries

**Review by ohodson — APPROVED** [review]

**Review by mikea — APPROVED** [review]

**Pull request merged**
