### PR TITLE
Automatically wrap SQLite usage in transactions and respect OutputGate.

### PR DESCRIPTION
**Pull request by kentonv**
Per the old blog post:

https://blog.cloudflare.com/durable-objects-easy-fast-correct-choose-three/

All writes that occur without an `await` in between are supposed to be automatically coalesced and submitted atomically.

With this change, the SQLite-based DO storage respects this requirement, by automatically creating a transaction.

As it turns out, this actually makes SQLite more efficient. Multiple changes to the same pages will be coalesced, and fsync()s will only be needed at commit time.

### CODE REVIEW

**Review by jasnell — DISMISSED** [review]

**Comment by kentonv** [comment]
I added a bunch of commits to this so that now we automatically wrap sqlite in transactions.

(It took me a few tries to figure out how to remove @jasnell's approval, which was based on a much smaller PR... sorry for the notification spam, James)

**Comment by kentonv** [comment]
@xortive I think we may need to do something clever where we store metadata about alarms both inside the actor's database and also externally in the alarm manager. The internal metadata always stores the _true_ alarm. The external alarm manager must always store a time that is _no later than_ the current alarm time.

So:
* When the alarm is being moved earlier, we update the external alarm _before_ the internal metadata.
* When the alarm is being moved later, we update the external alarm _after_ the internal metadata.
* When we receive an alarm, we check it against the internal metadata. If the alarm came too early, we reset the external alarm manager to the expected time and do not deliver the alarm event for now.

This logic will also be useful for integrating with the production alarm manager.

**Review by a-robinson — APPROVED** [review]
Hopefully we have a decently broad sqlite/D1 test suite to determine that this automatic wrapping of any non-readonly statement doesn't break too many different things?

Code LGTM though.

**Comment by kentonv** [comment]
> Hopefully we have a decently broad sqlite/D1 test suite to determine that this automatic wrapping of any non-readonly statement doesn't break too many different things?

Well, I don't think we expect to be able to migrate existing production D1 users over to this transparently, so strict compatibility is not really a concern. Also I believe D1 has been automatically wrapping this in transactions all along.

That said, is there some particular sort of breakage you're worried about?

**Comment by a-robinson** [comment]
I'm not worried about existing D1 users, just about anyone who would like to port over existing code bases that use sqlite to either D1 or DO's new SQL API.

The more big differences like this -- where any statement that isn't allowed to be run in a transaction just flat-out fails -- the harder that will be.  It's not the end of the world obviously, but the harder it is to port over apps that use sqlite, the more docs/SE support will be needed to onboard users and the less value we get from sharing the sqlite API.

**Comment by a-robinson** [comment]
But without a fairly broad or representative test suite, I don't know if we have any idea just how many statement types / applications this might break.

**Comment by kentonv** [comment]
I see. Given my understanding of how SQLite implements transactions (via the WAL), I would expect that every statement that modifies the database content is able to run as part of a transaction.

There are some pragmas that cannot run in transactions, but we're carefully controlling pragmas, so we can analyze them individually.

One odd one is `PRAGMA foreign_keys`, which is apparently ignored inside of a transaction. However, this pragma only affects the database connection, not the content, and therefore sqlite considers it read-only. So at least it's still possible to run this at the start of an event before doing any writes. I agree it's a weird wart, though, which we might want to improve... maybe we can actually detect this pragma and implicitly commit the transaction before it is used...

**Pull request merged**
