### PR TITLE
Fix a few spellos

### PR DESCRIPTION
**Pull request by ohodson**
The majority of these are in comments.

### CODE REVIEW

**Comment by ohodson** [comment]
Noticed the spello in `MANY_WRITES_EXPETED` and did a brief sweep of nearby files.

**Review by fhanau — APPROVED** [review]

**Comment by fhanau** [comment]
I thought about setting up https://github.com/codespell-project/codespell to avoid spelling errors from getting into the code base in the first place, but this certainly helps too

**Comment by ohodson** [comment]
> I thought about setting up [codespell-project/codespell](https://github.com/codespell-project/codespell) to avoid spelling errors from getting into the code base in the first place, but this certainly helps too

Yes, no objections to that. I have https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker install locally in vscode, but mostly just use it for new code.

**Comment by ohodson** [comment]
Thanks for the review, especially at the weekend.

**Pull request merged**
