### PR TITLE
Add support for counting invocations of now()

### PR DESCRIPTION
**Pull request by ohodson**
Bug: EW-7840
Test: internal

### CODE REVIEW

**Review by irvinebroque — COMMENTED** [review]
Does this include `performance.now()`?

**Comment by jasnell** [comment]
> Does this include `performance.now()`

Yes it does. That API uses the same API on `IoContext` as the `Date.now()` call in order to return the same results.

That said, I wonder if there's value is differentiating the metric such that we know if it's `Date.now()` or `performance.now()` that's been called. This could give additional signal on whether folks are just getting a date or trying to acquire a higher resolution timestamp.

**Comment by ohodson** [comment]
We're counting invocations of `api::dateNow()` here which is called by `Date.now()` and `performance.now()` and also from  some other code paths in edgeworker (details not included here). For the task at hand (EW-7840), I don't think we need to differentiate, but happy to go either way.

**Comment by fhanau** [comment]
This has been amended to make it possible to read the counter value when incrementing (not currently used on the workerd side). Also see the corresponding internal branch.

**Review by jasnell — APPROVED** [review]

**Pull request merged**
