### PR TITLE
SQLite: update to latest, support LIMIT on UPDATE and DELETE statements 

### PR DESCRIPTION
**Pull request by smerritt**
This PR is 99% reworking the build process for SQLite so I can plug in the right flags and 1% plugging in the right flags.

SQLite is now built from plain old source instead of from the amalgamation. ~~This requires pulling in rules_foreign_cc to drive the whole `./configure && make` song and dance.~~

The user-visible change is that LIMIT is now supported in UPDATE and DELETE statements, so if you want to delete some stale data but not spend too much time cleaning up the whole DB, you can say `DELETE FROM my_table WHERE stale=1 LIMIT 100` to delete at most 100 stale rows.

### CODE REVIEW

**Review by jasnell — DISMISSED** [review]

**Comment by smerritt** [comment]
New plan: out with rules_foreign_cc (since trying to make it cross-compile is making my eyes cross) and in with a bunch of brute-force Bazel.

**Comment by smerritt** [comment]
Hopefully the linux-debug and windows-debug tests pass. They failed last time because they spent 6 hours making very slow progress and then got cancelled.

**Review by jasnell — APPROVED** [review]

**Review by justin-mp — APPROVED** [review]

**Comment by smerritt** [comment]
> 6 hour time limit

> Tests / test (linux-debug) (pull_request) Successful in 358m

:cold_sweat:

**Comment by ohodson** [comment]
The build here seems very slow. There are a fair number failed package fetches in the log (network issue?). We have a cache for one of the packages, if this happens more regularly we should consider caching more packages/

BTW, the `-debug` and `-asan` are purely informational (non-blocking); to merge, only the plain builds to pass.

**Comment by smerritt** [comment]
This can't merge just yet; our internal tests fail with this change since the test environment doesn't have tclsh. I'm working on it.

**Comment by fhanau** [comment]
The non-amalgamation build is needed to do some configuration needed for the LIMIT change which affects the assembled sqlite.c file, right?

As Orion said, we should make sure to avoid the fetch-related slowdowns, which could slow down CI a lot.

**Comment by KianNH** [comment]
With the update to 3.44.0, there's some new functions which are enabled by default but aren't in the allowlist. I thought I'd just mention them here rather than make a suggestion/PR to add them, as there might be reasons for some of them not being allowed.

# 3.41.0

## unhex()

Already allowed.

## base64() and base85()

Not enabled by default, available as an extension (see https://www.sqlite.org/src/file/ext/misc).

# 3.42.0

## JSON5 support in JSON functions

Whilst this doesn't bring any new functions, it's a noteworthy change that might be worth mentioning on https://developers.cloudflare.com/d1/learning/querying-json/ (cc @elithrar)

# 3.43.0

## timediff()

Not in allowlist.

Part of https://www.sqlite.org/lang_datefunc.html

https://github.com/cloudflare/workerd/blob/7dc97db44a027046118cabe4a55a2bb6b32b1624/src/workerd/util/sqlite.c%2B%2B#L174

## octet_length()

Not in allowlist.

Part of https://www.sqlite.org/lang_corefunc.html

https://github.com/cloudflare/workerd/blob/7dc97db44a027046118cabe4a55a2bb6b32b1624/src/workerd/util/sqlite.c%2B%2B#L127

# 3.44.0

## concat()
## concat_ws()

Not in allowlist.

Part of https://www.sqlite.org/lang_corefunc.html

https://github.com/cloudflare/workerd/blob/7dc97db44a027046118cabe4a55a2bb6b32b1624/src/workerd/util/sqlite.c%2B%2B#L127

## string_agg()

Not in allowlist.

Part of https://www.sqlite.org/lang_aggfunc.html

https://github.com/cloudflare/workerd/blob/7dc97db44a027046118cabe4a55a2bb6b32b1624/src/workerd/util/sqlite.c%2B%2B#L185

**Comment by smerritt** [comment]
@KianNH Thanks for the list of new functions. I'll add most of those.

base64 and base85 appear to be shell-only, at least from my reading of `main.mk` in the SQLite source. They aren't available for making queries using the library, so workers can't use them.

**Pull request merged**
