### PR TITLE
[build] Fix Windows build, fix deprecation warnings with Xcode 16

### PR DESCRIPTION
**Pull request by fhanau**

### CODE REVIEW

**Review by npaun — APPROVED** [review]
Oh man what a mess

**Review by anonrig — APPROVED** [review]

**Comment by anonrig** [comment]
Windows build still appears to be broken

**Comment by fhanau** [comment]
> Windows build still appears to be broken


```
$ wget https://github.com/aspect-build/bsdtar-prebuilt/releases/download/v3.7.5/tar_windows_amd64.exe
$ file tar_windows_amd64.exe
tar_windows_amd64.exe: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
```

The Windows binary isn't actually a Windows binary. Great!

**Comment by npaun** [comment]
Very nice. Windows should have just used ELF anyway.

**Pull request merged**
