### PR TITLE
Simplify async context tracking by eliminating the promise hook

### PR DESCRIPTION
**Pull request by jasnell**
Further simplify async context tracking (and improve performance) by eliminating the promise hook.

Unfortunately, this does introduce a change in behavior that is incompatible with Node.js around the behavior of unhandled rejections. See https://github.com/nodejs/node/issues/46262 for details.

That difference is likely acceptable, however, Node.js' unhandled rejection handler does not follow the standard anyway. And this implementation is much simpler and more performant than the promise hook

### CODE REVIEW

**Comment by jasnell** [comment]
Well, in analyzing this, we discovered that v8's API for setting the context currently does not work correctly with Thenables.

```
const ctx = new AsyncLocalStorage();
const queue = [];

const thenable = {
  then(onRes, _onRej) {
    queue.push("thenable: " + ctx.getStore());
    onRes();
  },
};

const out = ctx.run(1, () => {
  queue.push("new Promise");
  const p = new Promise(res => res(thenable));

  queue.push("p.then");
  const p2 = p.then(() => thenable);

  queue.push("p2.then");
  return p2.then(() => {
    queue.push("promise: " + ctx.getStore());
  });
});

queue.push("out.then");
out.then(() => {
  queue.push("done");
  //hook.disable();
  console.log(queue);
});
```

```
[
  'new Promise',
  'p.then',
  'p2.then',
  'out.then',
  'thenable: undefined',
  'thenable: undefined',
  'promise: 1',
  'done'
]
```

This is a current limitation of v8 that is expected to be fixed. We could decide that it's an acceptable limitation right now and go ahead and land this, or we might wait until the issue is fixed in v8.

**Comment by kentonv** [comment]
Does the promise hook approach work for thenables?

When you say this is "expected to be fixed", does that mean someone from the V8 team has acknowledged the problem?

Personally I am just fine with saying that this is broken for thenables for the time being...

**Review by kentonv — APPROVED** [review]

**Comment by jasnell** [comment]
Going to rebase this and merge it into the other PR it builds on shortly.

**Comment by jasnell** [comment]
This will be included in other PR

**Pull request closed without merging**
