### PR TITLE
Improve illegal invocation error in the runtime

### PR DESCRIPTION
**Pull request by jasnell**
~~An internal PR adding the v8 patch to the internal repo will also be necessary here. I want to make sure we are good with this approach, however, before opening that.~~

### CODE REVIEW

**Review by garrettgu10 — APPROVED** [review]

**Review by irvinebroque — COMMENTED** [review]
Is there a world where we could link to relevant docs? @mikenomitch

**Comment by jasnell** [comment]
> Is there a world where we could link to relevant docs?

Sure. What link should that be?

**Comment by mikenomitch** [comment]
Okay, I just pushed this up as a draft - https://github.com/cloudflare/cloudflare-docs/pull/15541

Will wordsmith & clean up tomorrow. Link would be: https://developers.cloudflare.com/workers/errors/illegal-invocation

**Review by dario-piotrowicz — APPROVED** [review]
Looks good to me, thanks @jasnell 😄

**Comment by irvinebroque** [comment]
@mikenomitch — think the link would need to be `/workers/observability/errors/#illegal-invocation-errors`

**Review by kentonv — APPROVED** [review]

**Comment by jasnell** [comment]
Updated with the link to the new error documentation.

**Review by irvinebroque — COMMENTED** [review]
nice one, i am looking forward to first example of us going from runtime error => direct to docs

**Pull request merged**
