### PR TITLE
Add static file-serving example.

### PR DESCRIPTION
**Pull request by kentonv**

### CODE REVIEW

**Comment by kentonv** [comment]
Whoops accidentally included the actual config I use on sandstorm.io's server initially. I amended it out but the commit is still there if anyone is curious. :)

**Comment by ocdtrekkie** [comment]
@kentonv Would that config be useful to post in that org for reference now that workerd is open source? (i.e. Should we normalize people open sourcing their non-sensitive Workers configs?)

**Comment by kentonv** [comment]
@ocdtrekkie Yeah that could make sense. Wouldn't be directly useful to anyone but would be nice to have as a real-world example.

**Comment by ocdtrekkie** [comment]
I admit I still find capnp files a bit daunting at times, and I often default to examining other projects to see how they did it, so that feels like a very good reason to do it.

**Review by jasnell — APPROVED** [review]

**Pull request merged**
