### PR TITLE
fix(node:buffer): add missing atob and btoa exports

### LINKED ISSUE #2196: 🐛 expose btoa and atob via node:buffer
This should be a simple alias and there is no reason not to do expose it to improve the native compatibility.

Test case:
```
import {btoa, atob} from "node:buffer";

assert(globalThis.btoa === btoa);
assert(globalThis.atob === atob);
```

### PR DESCRIPTION
**Pull request by IgorMinar**
https://nodejs.org/api/buffer.html#bufferatobdata
https://nodejs.org/api/buffer.html#bufferbtoadata

Fixes #2196

### CODE REVIEW

**Review by jasnell — APPROVED** [review]
Might be worth going ahead and including Blob here too

**Comment by IgorMinar** [comment]
@jasnell good catch. added.

**Comment by jasnell** [comment]
@IgorMinar ... can I ask you to rebase to deal with the merge conflict?

**Comment by IgorMinar** [comment]
@jasnell done. please note that I had to add eslint-disable-next-line bailouts into the code because our current typescript setup is not great, or at least I couldn't figure out how to make it all work with our custom d.ts files.

I suspect that we should really be using @types/node instead of our custom typings here but that was a much bigger change that I was willing to bite off in this PR.

**Pull request merged**
