### PR TITLE
[nfc] clippy lint job

### PR DESCRIPTION
**Pull request by mikea**

### CODE REVIEW

**Review by dom96 — APPROVED** [review]
Nice! Would it make sense to add a `lint` command to the justfile as well? or maybe add it to `format`?

**Comment by fhanau** [comment]
With this we have two lint jobs: `Lint / lint ` and `Tests / lint / bazel`. To avoid confusion, can we indicate that the new lint job is for clippy or for Rust? (Ideally we'd have one unified lint job but that does not need to be handled here)

**Review by fhanau — APPROVED** [review]
LGTM otherwise

**Comment by mikea** [comment]
> to avoid confusion, can we indicate that the new lint job is for clippy or for Rust?

clang-tidy will also come one day

**Pull request merged**
