### PR TITLE
Temporary update to LLVM 16 on Windows

### PR DESCRIPTION
**Pull request by ohodson**

### CODE REVIEW

**Review by jasnell — APPROVED** [review]
Assuming the experiment works, this LGTM

**Comment by ohodson** [comment]
Need to up my foo with the yaml here, fingers crossed.

**Comment by ohodson** [comment]
Github action language...my PR here breaks Linux / Mac which then fail before the Windows build can get going...would like to specialize the execution flow for Windows vs Unix...it's going to be trivial once you know the runes...

**Comment by fhanau** [comment]
Issue is https://github.com/actions/runner-images/issues/8125#issuecomment-1691194433

**Comment by ohodson** [comment]
> Compiling src/kj/units.c++ failed: undeclared inclusion(s) in rule '@capnp-cpp//src/kj:kj':
> this rule is missing dependency declarations for the following files included by

Looks similar to https://github.com/cloudflare/workerd/issues/41

**Comment by ohodson** [comment]
From experimenting locally at home, this issue repros perfectly after upgrading to LLVM 16 (`winget upgrade LLVM`).

The underlying problem with LLVM 16 has been reported here:
https://github.com/bazelbuild/bazel/issues/17863

Renaming `C:\Program Files\LLVM\lib\clang\16` to `C:\Program Files\LLVM\lib\clang\16.0.6` unblocks the errors we've seen in our runner when trying to move to LLVM16, but then we have new static assertion failures. Without looking into this any further today, it may be that a later Windows Kit does not have this issue so maybe rolling that forward from 10.0.22000.0 would fix this.

```
external/v8/src/base/platform/platform-win32.cc(52,15): error: static assertion expression is not an integral constant expression
static_assert(offsetof(V8_CRITICAL_SECTION, DebugInfo) ==
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\stddef.h(47,31): note: expanded from macro 'offsetof'      
        #define offsetof(s,m) ((::size_t)&reinterpret_cast<char const volatile&>((((s*)0)->m)))
                              ^
external/v8/src/base/platform/platform-win32.cc(52,15): note: cast that performs the conversions of a reinterpret_cast is not allowed in a constant expression
C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\stddef.h(47,32): note: expanded from macro 'offsetof'      
        #define offsetof(s,m) ((::size_t)&reinterpret_cast<char const volatile&>((((s*)0)->m)))
                               ^
external/v8/src/base/platform/platform-win32.cc(54,15): error: static assertion expression is not an integral constant expression
static_assert(offsetof(V8_CRITICAL_SECTION, LockCount) ==
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\stddef.h(47,31): note: expanded from macro 'offsetof'      
        #define offsetof(s,m) ((::size_t)&reinterpret_cast<char const volatile&>((((s*)0)->m)))
                              ^
external/v8/src/base/platform/platform-win32.cc(54,15): note: cast that performs the conversions of a reinterpret_cast is not allowed in a constant expression
C:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt\stddef.h(47,32): note: expanded from macro 'offsetof'      
        #define offsetof(s,m) ((::size_t)&reinterpret_cast<char const volatile&>((((s*)0)->m)))
```

**Pull request closed without merging**
