### PR TITLE
Revert "Add toStringTag value on JSG resource types"

### PR DESCRIPTION
**Pull request by mikea**
Reverts cloudflare/workerd#1607

Breaks downstream trace test

### CODE REVIEW

**Review by garrettgu10 — APPROVED** [review]

**Review by jasnell — APPROVED** [review]

**Comment by jasnell** [comment]
@mikea ... how was the internal repo test broken? Does the test assume a particular output when an object to stringified? e.g. `[object Object]` vs. `[object Foo]`? Depending on exactly how that test was broken this change might end up having to go behind a compat flag.

**Comment by mikea** [comment]
> @mikea ... how was the internal repo test broken? Does the test assume a particular output when an object to stringified? e.g. `[object Object]` vs. `[object Foo]`? Depending on exactly how that test was broken this change might end up having to go behind a compat flag.

hard for me to say what's wrong: there's so much output in the test. All I know is that `Can log JSON edge cases` subtest fails with this commit and passes without.

**Comment by garrettgu10** [comment]
@jasnell It looks like the test does assume a particular output when an object is stringified:
```
Expected: ["[object Object]"], actual: ["[object Headers]"]
```

**Comment by kentonv** [comment]
It sounds like the test just needs to be updated, but it's important to merge those downstream updates at the same time as the workerd changes.

**Pull request merged**
