### PR TITLE
Use a remote bazel cache to speed up builds

### PR DESCRIPTION
**Pull request by penalosa**

### CODE REVIEW

**Comment by kentonv** [comment]
There are some "413 Request Entity Too Large" errors in the build log, is that bad? I guess it still finished (and in 7m, which is awesome).

**Comment by penalosa** [comment]
I think it's fine (if an object fails to get cached it's not ideal, but equally it won't break the build). They're coming from Cloudflare, so I can follow and try and figure out what's going on, and if the limit can be raised (I guess we have a default limit at the edge?)

**Comment by penalosa** [comment]
To follow up on the limit, I think this is just hitting a default for `workers.dev`. It'll only fail on the largest of uploads. I don't think this is a blocker for this being merged though

**Review by dom96 — APPROVED** [review]
Nice! LGTM.

Can we squash this before merging though?

**Pull request merged**
