### PR TITLE
Rolled Pyodide deps

### PR DESCRIPTION
**Pull request by Warfields**
There were structural changes to how pyodide_packages structured it's release tarballs.

### CODE REVIEW

**Comment by hoodmane** [comment]
Thanks @Warfields! I think it's better to just do the Pyodide release change here, the `pyodide_packages` update already is handled in #1566.

Also, the `pyodide-lock.js` should be replaced with `wget https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide-lock.json`. Though actually we should probably remove it since `pyodide-core-0.25.0.tar.bz2` contains a copy of `pyodide-lock.json` anyways.
[src/pyodide/internal/pyodide-lock.js](https://github.com/cloudflare/workerd/pull/1572/files#diff-7a7b00f5f38ea6d98b7b4c20ba422f27aae4c9b58a8ec829e70455281a5a549d)

**Comment by Warfields** [comment]
> Thanks @Warfields! I think it's better to just do the Pyodide release change here, the `pyodide_packages` update already is handled in #1566.
> 
> Also, the `pyodide-lock.js` should be replaced with `https://cdn.jsdelivr.net/pyodide/v0.25.0/full/pyodide-lock.json`. Though actually we should probably remove it since `pyodide-core-0.25.0.tar.bz2` contains a copy of `pyodide-lock.json` anyways. [src/pyodide/internal/pyodide-lock.js](https://github.com/cloudflare/workerd/pull/1572/files#diff-7a7b00f5f38ea6d98b7b4c20ba422f27aae4c9b58a8ec829e70455281a5a549d)

Thanks on the lockfile guidence. How close is that other PR to being merged? Both deps need to be updated to roll deps on the internal repo.

**Comment by Warfields** [comment]
Discussed with @hoodmane OOB and decided to punt this to other PRs over the next week.

**Comment by dom96** [comment]
> Both deps need to be updated to roll deps on the internal repo.

fwiw you should be able to roll deps on everything except the Pyodide stuff

**Pull request closed without merging**
