### PR TITLE
Change WorkerInterface so prewarm returns a promise.

### PR DESCRIPTION
**Pull request by danlapid**

### CODE REVIEW

**Comment by anonrig** [comment]
What's the reason for this change?

**Comment by kentonv** [comment]
Hmm, I vaguely remember someone tried this in the past and... something... went wrong... I know that's... not very helpful...

**Comment by danlapid** [comment]
> Hmm, I vaguely remember someone tried this in the past and... something... went wrong... I know that's... not very helpful...

Mike merged a very similar pull request in 2022 and encountered a segfault, it’s documented in the issue linked to the internal PR.
Harris believes that enough has changed in the codebase since that we can roll this out again and if we get any weird segfault we’ll just debug it and fix it.

**Comment by harrishancock** [comment]
> What's the reason for this change?

Making `prewarm()` return a promise makes it easier for our internal code to track the ownership of asynchronous tasks, which affects how many threads we will allocate for a customer. There's an assertion that fires when we discover that we have lost track of the ownership of some background task in `waitUntilTasks`, and the prewarm promises recently started triggering this assertion when we enabled a new feature.

**Review by harrishancock — APPROVED** [review]

**Review by jasnell — APPROVED** [review]

**Comment by danlapid** [comment]
Last push is just a rebase

**Comment by jasnell** [comment]
Let's be sure to get an internal CI run on this before merging. If you have already done so, just remove the label.

**Pull request merged**
