### PR TITLE
Implement Node.js compat v8.Serializer/v8.Deserializer

### PR DESCRIPTION
**Pull request by jasnell**
Implements Node.js JS api for v8 serialization / deserialization

### CODE REVIEW

**Comment by kentonv** [comment]
I'm not sure if we should support this.

* Chrome has never offered an API to invoke V8 deserialization on attacker-controlled bytes, even though it uses V8 serialization internally for many things. As a result, I'm worried that this is not considered part of V8's attack surface and we could be exposing vulnerabilities here.
* Even if it is secure, as we know, V8 serialization is not forwards-compatible. We have taken measures to account for this in our own internal use, but they rely on the assumption that we can do a two-step upgrade (first update the world to understand the new format, then update it to write the new format). We will have no ability to do that with applications. We'd have to instead control serialization version through compat flags. But, V8 itself does not maintain support for serializing old versions -- we have to maintain our own patches for that. Maintaining them long-term could be troublesome.

**Comment by kentonv** [comment]
If we really need to support this, I think we need to verify that the V8 deserializer is adequately fuzzed -- or implement such fuzzing ourselves, if it isn't.

I'd also like to see a plan for exactly how we will deal with the forward-compat issue.

**Comment by jasnell** [comment]
> Chrome has never offered an API to invoke V8 deserialization on attacker-controlled bytes, even though it uses V8 serialization internally for many things. As a result, I'm worried that this is not considered part of V8's attack surface and we could be exposing vulnerabilities here.

Node.js has exposed this API for *years*. It has been thoroughly tested and vetted there. Remember also that v8 runs the relevant Node.js tests for this as part of the Node.js support strategy.

> Even if it is secure, as we know, V8 serialization is not forwards-compatible. We have taken measures to account for this in our own internal use, but they rely on the assumption that we can do a two-step upgrade (first update the world to understand the new format, then update it to write the new format). We will have no ability to do that with applications. We'd have to instead control serialization version through compat flags. But, V8 itself does not maintain support for serializing old versions -- we have to maintain our own patches for that. Maintaining them long-term could be troublesome.

Yep, it would be up to the individual applications that use this API directly to figure that part out. That particular issue is well known to users who are already using this API in Node.js.

**Comment by kentonv** [comment]
> Node.js has exposed this API for years.

Node.js does not have our threat model. The application code is fully trusted.

> Yep, it would be up to the individual applications that use this API directly to figure that part out. That particular issue is well known to users who are already using this API in Node.js.

Yes but Node.js can be updated on the user's schedule. The Workers Runtime, as you know, is updated on our schedule, and therefore must try much harder not to break users. We would never be able to push an update that breaks V8 serialization compatibility.

**Comment by jasnell** [comment]
> I'd also like to see a plan for exactly how we will deal with the forward-compat issue.

The approach for this, I think, would be to extend the API to allow an optional `options` to be passed in on the `Serializer`/`Deserializer` constructor to allow the serialization version to be explicitly set the way we do for the internal use cases.

**Comment by jasnell** [comment]
> Node.js does not have our threat model. The application code is fully trusted.

We certainly could define some fuzzing cases for it.

**Comment by kentonv** [comment]
> The approach for this, I think, would be to extend the API to allow an optional options to be passed in on the Serializer/Deserializer constructor to allow the serialization version to be explicitly set the way we do for the internal use cases.

OK but does this mean we are committing ourselves to maintain V8 patches forever that allow specifying older serialization versions? And are we OK with that? Maybe we are, but I think that's something we should at least discuss with the team.

**Comment by vlovich** [comment]
Within the context of our service, should the serialization perhaps come with a signature that you then have to provide to deserialize so that we can verify that the serialized bits were generated by us to begin with.

**Comment by jasnell** [comment]
* Added fuzzing test in internal PR
* Fuzzing revealed a few edge cases in ReadValue that are now addressed.
* Updated to allow passing the optional version to Serializer/Deserializer as an extension

> OK but does this mean we are committing ourselves to maintain V8 patches forever that allow specifying older serialization versions? And are we OK with that?

I think so. Others can weigh in also, of course. I'm good with it largely because I think we're stuck with it for as long as v8 maintains their current approach and we continue to do incremental rollouts.

**Comment by jasnell** [comment]
Sadly based on the discussion on the v8-dev list I think we definitely need to hold off. Specifically while they (v8) do some fuzz testing of the deserializer it's not extensive and the bugs that have been found and patched indicate that their internal coverage of these apis aren't great. Ben Noordhuis (whose opinion on this stuff I trust extensively and implicitly) suggested that given how trivially he was able to uncover some of those bugs in the past it's probably a risk bet in the multi-tenant runtime. So given that, until we can be certain that the deserializer is tested adequately and Secure Enough, this is one Node.js compat api we won't be able to expose to end users.

**Pull request closed without merging**
