### PR TITLE
Implements RpcWorkerInterface::connect.

### PR DESCRIPTION
**Pull request by dom96**
Depends on https://github.com/capnproto/capnproto/pull/1586/.

### Test Plan

In internal repo:

```
$ bazel test //src/edgeworker/tests:sockets/sockets-tcp-test.ew-test-bin@force-process-sandboxing
```

### CODE REVIEW

**Review by jasnell — APPROVED** [review]
LGTM for when the rest is ready to land

**Comment by dom96** [comment]
Internal PR passes tests. Merging this.

**Comment by kentonv** [comment]
Should this have been merged when the capnp change it depends on isn't reviewed yet?

**Comment by kentonv** [comment]
I guess it's harmless since the new method will just throw for now and nothing calls it yet, but seemed a little unexpected.

**Comment by dom96** [comment]
Yeah, sorry for the unexpected merge. I wanted to reduce the number of dependent PRs needing to be kept in sync and this seemed like a safe change to merge.

**Pull request merged**
