### PR TITLE
Types: Pull parameter names from header files

### PR DESCRIPTION
**Pull request by caass**

### CODE REVIEW

**Comment by caass** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by penalosa** [comment]
Uhhh, this shouldn't have been closed @jasnell

**Comment by jasnell** [comment]
hmm... indeed it shouldn't have. I think it was closed automatically when landing @mrbbot's PR but github won't give me the option to reopen :-(

image

**Comment by penalosa** [comment]
Huh. Ah well, I'll open a new PR

**Pull request closed without merging**
